# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-monads-sorbet/all/dry-monads-sorbet.rbi
#
# dry-monads-sorbet-1.1.4

class Dry::Monads::Result
  extend T::Generic
  extend T::Sig
end
class Dry::Monads::Maybe
  extend T::Generic
  extend T::Sig
end
